### ISSUE TITLE
how to start static urls

### ISSUE THREAD

**Issue by caster1** [sammachin/node-red-contrib-ngrok#11]
hi whenever i inject on to ngrok node its starting on a new web url and when i shut the pi down and come back my tunnels arent there anymore in ngrok, i know its a noob question but so desperate for a solution.

**Comment by sammachin** [comment]
Hey @caster1 To have a static URL you need to subscribe to an ngrok plan at https://ngrok.com/pricing the basic plan is generally fine for most use cases. 

Once you have signed up you get an authtoken from the site which you can configure in the node, and once on a paid plan you can specify a hostname in the node config as well, its best to also reserve that hostname in the ngrok site so that you know it will always be availble to you.
