### ISSUE TITLE
Question - ngrok gives a strange popup

### ISSUE THREAD

**Issue by grawsom** [sammachin/node-red-contrib-ngrok#29]
@sammachin  
Hope to get some help to fix this one - and if not it OK.
I have used the ngrok together with MQTT where it returns the link in a popup dialog with link to the tunnel.
But believe that ngrok is changed, because now I get this before going to link.

![image](https://user-images.githubusercontent.com/6400532/215827582-38105818-2ec4-477b-bb71-d9118d189017.png)

But when using then same setup on my local pc I don't get this, goes straight to page.
I have now tested and found out that it has something to do with "token", but why I don't know, have the same free tokens, but why only one account works, and the others don't I have not been able to see through.
Do you know how to remove this info page?
I don't know how to do the developer stuff described on page.

I made this flow, with 2 different tokens - my "old" one, and some new (one I just resat) with no difference.
Token = 2L6P8THVBuwQBfvWPK4cUgtp9Of_3b7q37L6ieFtT2P5pzfbU
Can reset that later
![image](https://user-images.githubusercontent.com/6400532/215847180-ce9ede91-45d9-4724-a317-f22b73c6b43f.png)

`[{"id":"9128d06e7539ebb7","type":"ngrok","z":"21cbf7d91f44b2a4","buttonState":false,"port":"","portType":"node-red","host":"","hostType":"localhost","creds":"e1c4724a27101d4f","region":"","regionType":"eu","proto":"http","bind_tls":"","bind_tlsType":"https","subdomain":"","subdomainType":"none","auth":"","authType":"none","hostHeader":"","hostHeaderType":"none","name":"","inputtype":"button","inputs":0,"x":1230,"y":300,"wires":[["ce77a0a6829b5813"]]},{"id":"ce77a0a6829b5813","type":"debug","z":"21cbf7d91f44b2a4","name":"debug 15","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":1440,"y":280,"wires":[]},{"id":"6a18028059fed325","type":"ngrok","z":"21cbf7d91f44b2a4","buttonState":false,"port":"","portType":"node-red","host":"","hostType":"localhost","creds":"df59ee79790d092c","region":"","regionType":"eu","proto":"http","bind_tls":"","bind_tlsType":"https","subdomain":"","subdomainType":"none","auth":"","authType":"none","hostHeader":"","hostHeaderType":"none","name":"","inputtype":"button","inputs":0,"x":1230,"y":240,"wires":[["ce77a0a6829b5813"]]},{"id":"e1c4724a27101d4f","type":"ngrokauth","name":"FBBR"},{"id":"df59ee79790d092c","type":"ngrokauth","name":"Ivan"}]`

**Comment by sammachin** [comment]
Yes ngrok put up a warning page when you are on the free plan for any webpage that you are serving via their service as people were using it as a way to host fraudulent websites without being tracable.

As the text on https://ngrok.com/abuse says you should only see that warning once if you then click the visit site button it will remember that you've accepted the warning on that browser.

I assume that you don't see it on your local PC because you've previously visited the url and its accepted the cookie, or perhaps they don't show the warning if you're requesting the site from the same IP as ngrok is connected from.

You either have to live with the warning page or upgrade to an ngrok paid plan basically.
