### ISSUE TITLE
Issue to install latest version on a Raspberry Pi Zero W - Main process exited, code=killed, status=4/ILL

### ISSUE THREAD

**Issue by aiot-maker** [sammachin/node-red-contrib-ngrok#42]
It looks like there is an issue to install the contrib-node from Node-RED manage palette menu. 
I tried the install on a new SD card + fresh Raspian OS + new Node-RED install.

Environment:
Raspberry Pi Zero W (the old one - not 2 W model)
Raspbian GNU/Linux 11 (bullseye)
Node-RED 3.1.6
Node.js v18.19.0

Here is the console output (changed log level to debug) when installing the contrib-node:

7 Mar 17:45:31 - [info] Installing module: node-red-contrib-ngrok, version: 3.1.0
7 Mar 17:45:31 - [debug] npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-ngrok@3.1.0
7 Mar 17:45:39 - [debug] [err] npm
7 Mar 17:45:39 - [debug] [err]
7 Mar 17:45:39 - [debug] [err] WARN config production Use `--omit=dev` instead.
7 Mar 17:45:58 - [debug] [out]
7 Mar 17:45:58 - [debug] [out] added 3 packages in 20s
7 Mar 17:45:58 - [debug] rc=0
7 Mar 17:45:58 - [info] Installed module: node-red-contrib-ngrok
nodered.service: Main process exited, code=killed, status=4/ILL
nodered.service: Failed with result 'signal'.
nodered.service: Consumed 1min 37.315s CPU time.

I also tried to install via console with no success. Node-RED always enters in a loop after the failed installation.

Node-RED can start normally after removing the failed node with npm remove node-red-contrib-ngrok --save

Note that there was no issues to install  the previous version of NGROK contrib node in the same Raspberry Pi board. It seems to me the problem is related to the latest version of the node only. I appreciate any support on how to get the node installed.

**Comment by sammachin** [comment]
Hi,

The new version of the node now uses the official ngrok js package, this package only has binaries built for certain architectures, and the linux arm build uses ARMv7, the 1st Gen Pi Zero has an ARMv6 chip in it so it won't work unless someone builds the binary for that.
I don't have the expertise or time to do so, unless ngrok themselves add this architecture then I would say support is unlikely.
The 2.1.0 version of the node used an updated version of the older ngrok library (5.0 beta) which I think would run and give you support for the latest version of the protocol ngrok is using so that might be your best bet, but both that line and the underlying library are unlikely to get any fixes or support.
